version: '3'
services:
  shinobi:
    build:
      context: .
      args:
        SHINOBI_BRANCH: master
    volumes:
      - /dev/shm/ShinobiRAM:/dev/shm/streams
      - $HOME/Shinobi:/home/Shinobi
    ports:
      - "18443:8080"
    environment:
      - HOME=/home/Shinobi
      - DB_HOST=shinobi-sql
      - DB_USER=majesticflame
      - DB_PASSWORD=1234
      - DB_DATABASE=ccio
      - SHINOBI_UPDATE=false
    restart: unless-stopped
